apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cliproxyapi-config
    namespace: cliproxyapi
spec:
    secretTemplates:
        - name: cliproxyapi-config
          stringData:
            config.yaml: ENC[AES256_GCM,data:nj1cg4lq3NjlFViYKERfQ2tZwTBYGtz9E2jOmSwgb8uhiAwcujboJS/WWYzPjVC4xOqTOqiMASoKRwUqkskYVvS0YZ5rsaMsWQvwa/9MChiJ3eWN7Y64o7w9H3E5uJucFRX7A9qzzeOPw6LMg/v5CAFME+QyY4TpcO8tbdoEXOGlSUb0mj1vIuMl+I5smqvMB/8ULdLuTbtpEjg1BqPvEO2YU4yOHyz1+UO9YWkpg0Kp09lh8ew5ZO8/sCBKgAzzKTvHmz7iunrN6boTo4OvL07tQuOdeUnuZSCGx2CZRa6fSJHMW7YId1DVlvpYxDXOINcGR7DcvsPXGzLDcO8m/AU1Iea8VMO9xvGpq64A8XQQOHUPQspgFvC7jSbnkm5mEUN2ZdmBRl2bGtSLhNLfJne3LTqvcBvMmVw3VBRZbcTwskc7hZve2vyM9+xh1RLcW1hv67UEht++D7hOjcXyQX2630jUyD0MOglyTAveNxJm5ZjujDPXXHRb1XgLhQ1QtO7+7yQLGvHlr9Zr+FQdv1lzqRaLfXrlMZbGPRZ4h0mArk+ACyw/f+ZMwyP9nkyhlAtCaNPJqDV4tIJu+8znOPMEwM1fiZ70qKDGBrOhtoDqWRJEpDHMAwyJu7OAZ6YdPzi8xqMOlf1X/X262HHo3vsV5mtul0bLLtSU0GRkz7/dMBesQq+3Z0EbitLomjNLAqvKwr1Dk4okEi8eY6qrxaNGq1u3+VKz7/S+v1TiCfA2yuj04dQi/5eJ1oXO6YkN9z7ny6tRZfbuA95fF4YRAGE7daRA7VBh3hbmrrCT23Xt4pJs5McW0GRNxtIKdP51hGcUEcRdXu/01t2v280KHdqYN9K5sDkQ5CxxLn3ZPfEW91zpAOwbfOdeFUvHsxg/eflpVheYLh/cwdmRu6affOUjxPPZR/AKYVVRK7kDnvdBWF3mvmk3es0hFnpEMtbiooJh8KpsQqsv3pC5uWM2xopvj0Tzt78=,iv:27u84myX1s9TzhubNNM5g7lJ4RgXcrOp+/Scu3V1was=,tag:Os5ou4NXW+N2CaGqblQNSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6z3qj3swz7g6c5qtwtyuzvm7nvxxjlvmuk8mnk00zc83yazpp7q4r0fpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBic1p3em95elo1UXdkTHBj
            U1Jodm9iVFVnVU50TnhIam1adFFiYTA1dVdRCi9ObDZtbS9QSXg4MjVsYlV5MWky
            TDhnbGQ0OVdBeDNKV1Y2NGJ6N1c0K3MKLS0tIFpocFJMdkR0eHlScHRZVm1TTEZs
            anZWQ1pxQWxsOXo4SVlPb1NSQm5Md2sKbLB9Zo75KJmpAlRVyqzYjuKD2IQ7b1DI
            kmVKCRhx69fZ5aQ4eeyagHvKrSDeDR3LpVwZTSPrKQcN4HW63tqoLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T13:37:37Z"
    mac: ENC[AES256_GCM,data:IY+cks190wOl5q+frHb/SHRGS1pCHKPI259f/YNgWUJHvSTl1xX9NrVkvamhIS82wmP99qmKNthOuHi/vAMLLT861OwfEo4lQrxJHBmAz5G37dkSHLYrxgrFHlg3drgcNRImaGNoyLgcaHO48e+LlQOTG9a/91mnlD721jDI2r4=,iv:Q3JGJ1nsFpp5KPWJlcTyl+92M5ksybOHzJbL94FAalU=,tag:MNbK/op/QXVqQiBy/FIXiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
