apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cliproxyapi-config
    namespace: cliproxyapi
spec:
    secretTemplates:
        - name: cliproxyapi-config
          stringData:
            config.yaml: ENC[AES256_GCM,data:XwQU1N4ktshBkhPMFNW/9eaIxA/JWbbob0Uu9mIgIOyRAtytpgkoj10BlELUXrRpiFq3ZgqI1c1acOKqsLP4OYzhF86m/ejWaIhbA+JxQhLlRgyqaNdzQUU6PUBRc+mX66FWCMNs++lE8M/gAnvgKUEGZwX1YDE3xGxCpYj1h85w7VlmoGM5T581WhsVhdPu7y1XJJ6NS6r1mlgNxj3y7bX60COg7MKoJTkaH9GKq5Ia3YTEEpsGz0a9t3G2tn6GcYlNpwaFUa9zHc/I3WrcjIdXGlTtD8UxAP0D7vSCR6LUwFPwAY8nrh7Gb81/CyPcpHyDUyyzhVcWSw163uiwpeYMKMW+8lxm8m+x5qi12I4kMSnNPtGS1NUK5/edyY2HCgGu60stSM0vPQlcew2Wb8Oj8XwTzVlZZ9rOFK/mHJfLLwlX9y4UhzCBR1Jn6tKz6rKl8dPk2RGmm+enElsBnNlXS6nt2jZr/42oG8AOkOaMA4FQZWDHME9HXpLEys/gImoFO+QAymXFqLeYkvEf0sOrx8+wYCiK7OtqheZ/Q+AiK5L4OMNnD0F2ulAJZdeO86e5kdHn3/fYmm+9lCKUVppn7w/XqjHOhNcXfsVmPzSF5kZi/liTIQibINQ2Un2KZHsDulqnE+cCTo83y+izs0iW770D/913Cq8fRDd8P6ZLgXff+i+CqSMwP6ws1/zjXgu4FhKn6p4CBPqUhMeyb608hMNyav9CVRzgwCWxqvnc4DKNZa+eGBE8nkiTO9aSeloEy7nd4tGanYiUn4TpquphNrzw/WYNNh32WSlHHW4DWEI4go+RD7pAqIGbHobL3vfBPcSx5CAKNS4/yU6oReHWBaELa7ZsGdUx+jhOc+cRPxlmJp92gewCrCoDP3V+9DZvMHNObpUKipf2PUFcTSvXxOajk0nJneNM55bQpxpPRC98Jd6UhWZFSR8YdCfbVtZQqwy1DS2+72y/riwLrrZbeu1XoL7iCZAwrqurvcOOtiz6HgFy9ehyTMuOU0rIi/IH0hDACqE7vCIIW4fdES1XZXFsW8anzI58SWEL3tgv4kPDMUNwicq56tIRwEr9CYJsnQ==,iv:CLDc7rjoEspih8Ytduv9XvAUwQZ+0eQjPaJomaeBfuM=,tag:CtqDcumf4n39W4HBLJQVAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6z3qj3swz7g6c5qtwtyuzvm7nvxxjlvmuk8mnk00zc83yazpp7q4r0fpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVE8rblY3M1hxQkJjU3hi
            cjJiNGxWanVJZE9EVkI5TzdPcnNoREwxMGlZCkFDYWhtdkQ4WlJNalZ0aFAwdGZt
            QlNCYURkbUs0NzViN1VKbXNUakpFeEEKLS0tIHlsR2IxSXMvWkUvK2QzUitCWVBm
            bHdYWEM4TDFkenVYeTZGMXo1NzNvVkEKQM0c8vpY5kM7rAyncC7DePtu4MDQ1HKu
            gdCxTV6jqYkPGaa8LutajMWSEOgJFwjrRoojEyxQ1JKsOXw28+3M+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T14:20:14Z"
    mac: ENC[AES256_GCM,data:2FMQ9lcElNaENdEff8IxTxYFa1HjTS38ahzmHvMJ/j5VgaG0E0eg/uH8+vblCUj31tDW0RXqUJ3qbi63GZ26OlDQ+mzZfjZcESkI7SyD0lWplg2iSNmKazkFin3+o4S0/adzaerlalspMJ79+MsqyVdzh/o0zIiorrFZ5O9CbaA=,iv:YI7wJNljr7Yy7li+xjmBh0Pdan2nujchd1a+XiuJnQs=,tag:QFOA5txE1m6ki6oqjJCeYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
