apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cliproxyapi-config
    namespace: cliproxyapi
spec:
    secretTemplates:
        - name: cliproxyapi-config
          stringData:
            config.yaml: ENC[AES256_GCM,data:s/lAJV/vrfa15YchYIHLgOrt+knWdUGoM13hCtmkA5bQhuAmMfURQD+0UoF9oDUyQ0i5hNuVg4ngMbQy2dcLf9Q1aJGVqMhj0UXZ9pv+HNJ4Iik9DVWgO0Nb9RmCFEd36J6ZpTvIg8UiCt9GXgH1n+Qpcwq24vjJitw1jdr/9ZdPgf2v0t5kPyWSa4Zpd5rI1HYmknILLo+N34VeHVfzCigISrZJk6a/iaDr0C+TdS89sP6+Liw1njN9/UxKRNfvz1AVz46c9it2Lajdrj+hJjln1oHTjuwOjwEXL2Zt7RRuWHZYc+6FJUw+YH+U/My7QT64OV37JNlfIZ7ymZrccC9Y/Rlm/vZcVP7dvJbyd9Xub6Pw/rB09Z+vGGLLOtjGT4i7xBSxUfuwr/ujtGIbJnALzuPaXj8VNO00pimJFDqvoHwaOtjABRyuw7I0SXAjY+Q5es0Lsfhlx0dYBp8lmdNHasJXG2+3jTWKxkbpng9sPVtveH+JHg1cDiGpQXZh2XerJro5G8ISpcc7ZjaZKlaSCGVso+wU/Ez8Z/n0aSfgaPUbiX5HtU2x89aw5KlIR4WrL+1yfAhN2vAMtE/fmkaMwx/RFOh3ok2dGncDFSLYrA5C7T8VTMaQQS07Hl3AXJ8d2kn7zpn9ZqCaVqnCngrp6QY88V5LkBzU411LJZCpRDME8lGCGK3//VeHXhpL0iMePfnNb12ptseeFBT9/6CFIo4MIsDkOGX/kv1rd2iiUNBmfOC4ugAyJqU3F99I1ay8shkFxCf33NU+P3u9O9tXvmYN0W2tk6IeBKLsO4V2lBxmtsbgYQ3K0Wawl5YfJX8Wnc+qfCgjHWB6e9OCu5f0/xoT5g0PkpewBUlRp7svcyxcBSNp4yssdok8uJ5Kw5DYF3tDpA88wi2f+ZtTfAD545x3TgzLUMGLOsReEbIuQrVdsapTIrQ7cwHJN678ToGwxEae56sU9p0FbpDzhn5VRUXtIblTy64N2cz/xc2RjCwTGJ9gIxyrSUPhDxxoHGKajO7IG/T0HzsHzvUVJ6gieNIKNs2iqlGa+uUHAgdRdDOUX/p1rvD35AxGsXhbKHhH/bd5VtugHYsq3cmURs5FPO2sq3MyRTqFyeBms2MsEPU=,iv:s3usiI0cuW/ZLeadyeCcIU9KMiyG1FMR71THV6w3E8M=,tag:JvhMefPNfCEojsADn0AfIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6z3qj3swz7g6c5qtwtyuzvm7nvxxjlvmuk8mnk00zc83yazpp7q4r0fpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVE8rblY3M1hxQkJjU3hi
            cjJiNGxWanVJZE9EVkI5TzdPcnNoREwxMGlZCkFDYWhtdkQ4WlJNalZ0aFAwdGZt
            QlNCYURkbUs0NzViN1VKbXNUakpFeEEKLS0tIHlsR2IxSXMvWkUvK2QzUitCWVBm
            bHdYWEM4TDFkenVYeTZGMXo1NzNvVkEKQM0c8vpY5kM7rAyncC7DePtu4MDQ1HKu
            gdCxTV6jqYkPGaa8LutajMWSEOgJFwjrRoojEyxQ1JKsOXw28+3M+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T14:23:29Z"
    mac: ENC[AES256_GCM,data:TOQqeqGY6aD5s+hBzy7/8XUf2zJxBALPeaHQ3PbKNtwpuu/UvOq0hSmANGZrwALnqT3XV6GqIOBdETQ3S7gQq5jRaZvfVqw9Y3RXgeX9RB0dDrwrbYhfNy+ZNN/X0qKe55RoqaNizGq6PrzljXfsHdyZD5EWIjFNoqZ9u11qmUs=,iv:JgSd4VAKr8gGuOqSfFPSHD0RvA5lert9wI9YumrOH90=,tag:7h243vaMGC02eyROaCM6Hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
