apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hermes-env
    namespace: hermes
spec:
    secretTemplates:
        - name: hermes-env
          stringData:
            DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:GQJ3ppS1Igps+go2ksos2si0J3cBRg04jwcl5LPEjNbYWP/VKP4aob2sGqrcLZluM7Z7rSr4YwZDC69Iw0swCT8BtV7kPUjg,iv:2cdq0XqaJVG5j8djAbyot83uzjac6gzs8fWwqfnpmZU=,tag:xAAWTrEqNZUpCnlWSVWhoA==,type:str]
            DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:1kwqtUWrluKoh1ea1t0AkKIP,iv:aBwfAucbzWjVZwh/yU8Axub8vLSEIUXUAiz/ba8+0HM=,tag:oEZAIa2jAhMDBCt3m9iGWw==,type:str]
            DISCORD_FREE_RESPONSE_CHANNELS: ENC[AES256_GCM,data:b6ODT0mi/9cF/a33H6hPIXcGhA==,iv:X6ay/yenxII4RCNsOPDsxvYf+7kiCtEtduxvdPYWtQI=,tag:hfkE8E9o0/tfUuQ7tVWX0Q==,type:str]
            DISCORD_HOME_CHANNEL: ENC[AES256_GCM,data:0SRgL+ktEOeQXSpxiGFbEOY5fQ==,iv:wZJ30BVurnPo9wQFj4OCxi15R+hl0xCCKYx3vrdBS48=,tag:rT/OpImNP0JXdMUXiMwipw==,type:str]
            DISCORD_HOME_CHANNEL_NAME: ENC[AES256_GCM,data:8KocV9UbDA==,iv:2qfnvQ1SYSldqV+QOYvaf2Kdr8y4Am+oXtNNkN3YAtA=,tag:YPqpSPXLgxP/V9PZ6X+rKg==,type:str]
            DASHSCOPE_API_KEY: ENC[AES256_GCM,data:sfSIYQ805qEkkJMJ7rbXrybcLVTX+X+7ilKsRDuH/cty4HooELi90Cl+6+NqMfOgwHANDSUX/AydCAbQvT5Gl41L1OX6iH5AIza7Ujyoq3LA9STfaWYxW1VaNsptbwYFAln2wwy5G1ALBKUi0D2IJRre,iv:8+st28nKZhZA2t1lpXkMthovef6f3MKXk8mMSEOM87E=,tag:sbF4Ynjmi0tAOPpOhhcKSg==,type:str]
            GITHUB_TOKEN: ENC[AES256_GCM,data:IZVtT0y1JhXMtUSvablr0jUa4nTVt6J3uiiXJTMzftX1HEpQtf9v61WRaXYuhlpcMU40+3u6jpPPe8724X9jRGqIom/JIS3dLsI1VmdUWTFjUxR1cSyoJuXNV0X7,iv:xXO/BT2qL0UlybpbrrKBytNA8ftGcGwKxaQd6TNRuY0=,tag:ErVV/GH7+mVTwJHxeWmJQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6z3qj3swz7g6c5qtwtyuzvm7nvxxjlvmuk8mnk00zc83yazpp7q4r0fpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQUR6YmpLR1NrZXNFYXZ3
            ZmczRGF6VUdIRU92amtpdmRSU3k0aGlqd1RvCjlZaE1JMWRFM2JmSW1aTVFBNEdx
            aFlibndiM2cyamRydzRTeko0STFyaGMKLS0tIFdJdVRaVUVPcC8wamtnME54M2Rz
            U0tOdWpnTnhPZGkvVXBsTitzRUdLNzgKbYGI1gsQCgb+RDPc5vFCfl09PWaPWsIv
            sJVfmaUoukVQMvDHvb422zhYmtc70kEEVXEFTTXUX2D6Pn6X1Q7N5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T11:25:52Z"
    mac: ENC[AES256_GCM,data:EbzL5lTHk9jRPcR0u3YCUMw+8w969uleQ25a6J8fUbQHSzkpnhTauNhN63o4yjc4t/tPHuEyg8Tjdm3u8NyVo3+8/ERzGXTx+bWxWRyhTMTqnMRHUXC6YPWQSPRZ9hc/ymzHS/gja/29CYDXxSNmJ+0u1DpmvzSso+0yZBmbhmY=,iv:UZboV+zPwZkaivXBUhMHYP3fT7Zd+rfY5wJ5f61k0WM=,tag:eI/FAnBp6xh2HGtZ93fifw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
