apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hermes-env
    namespace: hermes
spec:
    secretTemplates:
        - name: hermes-env
          stringData:
            DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:47zAPiFRJOcFsOFPIKBq3Lh9wYiAfST6XfrfUS2J066XRiy11us9LHoZcE/MrPUMsoiVzKWL4GP1oY/aPSQbKVleGui7maXy,iv:IS6y80Cie02Vsoz7gjI/1qMpHqQqVALtJxHbxdDU5Hw=,tag:nnP8uLZ6Z1uEqFwhvWOaKw==,type:str]
            DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:cb/D4/A7jvUCn2Yvrlc6/svk,iv:usMtN5ho95eJbgiYd9FHLAFPuf00jSqgvIn+zbdnmpw=,tag:ZATOfEoip5lheQpC+ALFBg==,type:str]
            DISCORD_FREE_RESPONSE_CHANNELS: ENC[AES256_GCM,data:G67vYk2Nyee/lGtRhxwperxUUg==,iv:dK5T5PS51L07Kto5mJQfHMEhfKK9rwCOUr3M9QEQNBA=,tag:OAXvRC+8eMxZqXfbutDnKQ==,type:str]
            DISCORD_HOME_CHANNEL: ENC[AES256_GCM,data:PQ749vOe1Nw8UL8+AXg2LNPpiA==,iv:767M/mYN6h7JeQRJXO8tM0vJzlYna20OppwQV3J0yWU=,tag:pAq20XJvjYMTK4yxQVfiIg==,type:str]
            DISCORD_HOME_CHANNEL_NAME: ENC[AES256_GCM,data:a1lbzDzfQQ==,iv:UnkykMEsjqi3D/lu3te5T0bT2nGyhVStBsy2jVpZl8g=,tag:35KBAEsOys6nzjiDb7H9kQ==,type:str]
            DASHSCOPE_API_KEY: ENC[AES256_GCM,data:novaqIxD4xrMhbMn3Zmph6/Zx3G0BVczv8/xokj++3ACMsNJ/ijT+6yV6WVye0Kr3ae6eTXupcwxcnBxUKf0E4yCnaYhDhS66qBS8KjXRFRgfjj5X35aysIM6KQIvQ2F0MqM8FPVvH1e2h520JC/GU7Q,iv:jIElUc0YCy4pC01K8maZAbM2v+Qvkdktgas374fMmTA=,tag:wfyiiy/AWLwGxwvZIzlkGw==,type:str]
            GITHUB_TOKEN: ENC[AES256_GCM,data:lbyB3Qb8jmU3T8B8u6wYpRp0JEntCmJkskIUk6UXAKomOotMoV/WzGQBzL8Dm8zx0LobnQiUxMnYleUS7GShwC73JhTAJcD1M2sg0lMDMVNHlGWUCwbNXGTnBmQd,iv:Ujr+cEKuEY4C5oSuwhNa7Ncq+R+BKiiPtEA2DoOKN9M=,tag:ZgJeXxFsmspBh3irJbZC7Q==,type:str]
            GITHUB_TOKEN_OPSIDE: ENC[AES256_GCM,data:eA6gwBVf5AbX0KLNJ98FO3WKFYnBf1jh+dL30Uzx+YcN/R0SX4EMSv5fN9yfJfCdI47cn+cKccR5R8OgaGsQAjV93t7LTdbH4mZTdB4xe+THF3FL/73IJBUOMcgA,iv:GBBmr5rkiI4mhbuwgoBVkRYnYE3CyEPdjEDq9Oomk+Y=,tag:aqYfeRcUbYOhvZQ47/oy5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6z3qj3swz7g6c5qtwtyuzvm7nvxxjlvmuk8mnk00zc83yazpp7q4r0fpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OHBFZ0RmcUdNZnBVRkRS
            TnUvYWFHVkxEWFdWUFNxRXdEZW9oT3c5V0NJCnlBOTdKT21LZHNpNndybTcvVVBQ
            NFZQbVBualFCQ005SmdtNFZMVDlOL1kKLS0tIGwrb0ROYjZGV25XbDlTOW9JVFBJ
            NXZMckk1cEtHZndmOHBmdkR5UWI0dzAKfwiRU8UBq7uZhG9nzKKINsPCzoTlbIwA
            zSa45uBSzwM9lrBa37wszL4UI2Hf5ioConetKIJ/roPTmryVy8SREw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T13:06:41Z"
    mac: ENC[AES256_GCM,data:f5ZHH0gV3gqLPKq7myXzsQKR+BSPnPYG5Qb5+CRaG7Z8XLFBj+A6vjcXX+LOWwQrId9p4am3CpR0DhUsUFN01UjQ+VXH2/5nQPeHqUhdhhd42/wY0a29NNcy3JxHolmYj3eq/TcXwl4TKSBHffq+1MyPKT/ysFdQshM+KvPOxvE=,iv:08Q1CwoRXQFKVTki0K5NaXms/hD0ckBXlJoqblUhysI=,tag:dhfx8BW8WlhMACboIOp4lA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
