apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hermes-env
    namespace: hermes
spec:
    secretTemplates:
        - name: hermes-env
          stringData:
            TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:OXRSeZ0lvbHYsbhLr/2GcCWnSX9hSFjN0yhnNEpr6xq2trscn1oBy6a8OVT40g==,iv:1HJ5oasDLFxWnxZooBjRbG+c102W+o4MoCO69BgbvZ4=,tag:NnMgicJu4A/mNMpuiprncw==,type:str]
            TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:C8OuNUS1MkzdBA==,iv:mCcm1HwbKzwB5E7KXwcRU7AbKZWkwHGUagIwkOcnJN0=,tag:IKPoDaD9WIZRaJTAzrlbyA==,type:str]
            TELEGRAM_REACTIONS: ENC[AES256_GCM,data:2Uyghg==,iv:gtyFBr1RtNiSKAW76tHM/z/taG4BpJdrKpoXvfa4KJw=,tag:cw2o5yStgyPQnI/CUak9Nw==,type:str]
            GATEWAY_ALLOW_ALL_USERS: ENC[AES256_GCM,data:D5Xknv0=,iv:xVzC82htIJJRasMwHMOlsD3s0FV4EZP9OXg30tRW740=,tag:8uklUnrVn8wHJYTL12wyBQ==,type:str]
            GLM_API_KEY: ENC[AES256_GCM,data:7KhpxQFnosAMc5YZz/mp+nQ625QAvg3oxHYgOu0UtLyh3rLrqr86DuANJDRQxFCHKQ==,iv:zsuYGJvu8NZG7kNvYWaLK6BHiv8cXPyQIO6ZDjBgnLQ=,tag:b6vyERccfrJn+A/Ycv5ghQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6z3qj3swz7g6c5qtwtyuzvm7nvxxjlvmuk8mnk00zc83yazpp7q4r0fpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSHRMYXBXWnQva3Mzbkox
            VWZKdDhvckgzaFp5ekxmclFjOTFBYVJUOFJNCnBFdmhmK3pjZTUzVndRQ25vWWRj
            aVZoTXRoZVpoZjQvczFnUWQ3NWFJenMKLS0tIEdBZnlHdnpJTmlXbG16WFFlaVMr
            anN1cmNsVG5wZG13MXFFQjlkVGpUbkEKzqmxi24d+oDZnu2Hu4Dl6tJhvR5ITmLI
            k8rrrVFohq2nC2rO/M5VPtKaz4dkZ+TXZseqbi1XsGQlKEyGX3YT8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T16:31:36Z"
    mac: ENC[AES256_GCM,data:4MBMpTMysxDUcMDE23KDhp9Nupn0sfdLSkJtMkj6nP+ZDZ9TzeQhJEvMllmKBcTpuv5yhQVOCi1k10KtZeZYoa5AWfyRwjrNupj9hLipN82FCntKcqahOp9KFKHXqRcOa/RCohAUASpkB0zGLRQ21duuGvvRjHHsW9g0WFbzH5M=,iv:VCv7HU55Nr1dPiC4/VzPaZfGhy46gcWnQZKZYvoj3As=,tag:3pQ8m6gh1CdehrNhPywcxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
