apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: folio
  namespace: folio
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - folio.tweak.codes
      secretName: folio-tls
  rules:
    - host: folio.tweak.codes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: folio
                port:
                  number: 80
