apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hermes
  namespace: hermes
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: hermes
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - {}

