apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: folio-runtime
    namespace: folio
spec:
    secretTemplates:
        - name: folio-runtime
          stringData:
            GITHUB_TOKEN: ENC[AES256_GCM,data:XPIUfNfUfQMpXni03uSiI8WXcXMlHVkU3AODiNRt1u3Ft9/sOWhmeQ==,iv:XqTYlhdUnPUEoMgpzrpwJRmwT83eo4+R8R8i5ovihtY=,tag:q33ycregHkERgoSq292dGA==,type:str]
            FOLIO_API_TOKEN_HASH: ENC[AES256_GCM,data:WvxT4cWBAvxoR/RfvlLeIvceV5XuE8GzcDFBzCE4kJebJP8LaasZYziUen5L4H4852kKMOCTFR8jVHTNG9CbEQ==,iv:UuY7wvFe+jKDjVMcaZxpuhNh03ewwPCpXglFxz8AocY=,tag:3PtRpJ0DEnIAcUiGts/59g==,type:str]
            CF_ACCESS_AUD: ENC[AES256_GCM,data:k2tEQ2IbNB7Z1sxBey8rByW2atKc0hha3VmAZdYBSTI1tQOpXQqzhs0IZAx6kSbuGGZpWNgpRd//9lgP+C110A==,iv:XC/JO1wS5wWn4Pii4AQXCkQmsovKwoXDI/LMJ2qy/Kc=,tag:IdApZA261qCe0+iiEquXGw==,type:str]
        - name: folio-ghcr
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:D7a45YqxD9Hb1lrPR0wZEonf7ER1rdQwFYccIZkQSG0P6f7rar3ORle/YQkS6EltgAU/ft1n5BldcmEIpzayfnDUcLGsPg1oCZNEK9/YBNlJUklu+0tvP1Png9un5upp7hzadJc=,iv:9mbDQgffJwjhhmlkC4YwiWFRqUu/NY7pOnteqcvOR4M=,tag:zDabsHnSwV43JA7wSlovYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6z3qj3swz7g6c5qtwtyuzvm7nvxxjlvmuk8mnk00zc83yazpp7q4r0fpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzR1puRzB6YmFKcXMxdjFK
            VnVSNlF4d3N2WUljWG41enJEWlZJZ2NWdFEwCmh3SDVyWGJPbWZZK3ZjWmFyamJJ
            RHY1aWMvb0paYkljNGlVbUNuVlgwUUEKLS0tIHVPZDNBUG1BU0RhdC9lS2JtVTNl
            VXZEcFlEb1lGWjYxSWE5QjkwUFl2VzgKdBUCd/A+YOjmfhj1zHdV9Y3YfHJamGhK
            YVhG5jlKhL9BdD+f0l0D3GkDHIaNfG4NZAcrXGrXmO89zZvgoN3BiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T08:35:58Z"
    mac: ENC[AES256_GCM,data:HKKc84ThBKhHfhI0e49kwGYSp4ozVRoNkv8UW3WCYto5v+8a0O4f7FV2U4IA/5XqRBObxcf8L6KNn8tKrwGLwwmT9WCeCjZSgAlpjGdeybN2j6TfamH4u9rytUMyOC0dUEqPBvn+EN0phBHYzjfqF0V7fAzoplfi8DzYAa7zfc0=,iv:GpDYrU7nhQxITuI3tiqnnldXDGAzy/gfoLSDRLLR+vI=,tag:qDOhI87JNE2s9kSQzdiFhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
