apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: excalidraw-mcp-runtime
    namespace: excalidraw-mcp
spec:
    secretTemplates:
        - name: excalidraw-mcp-runtime
          stringData:
            MCP_AUTH_TOKEN: ENC[AES256_GCM,data:rTP0yH4y6tGHhKlHGwcqWu07xUCmqbBEbDjNvAyGegwYN4gzMt3zuOS7Cg==,iv:KDt3Gk/w223iywEsmh/FYaMrfqJBp0n1CJ69csX8Lww=,tag:ofOjyWKUnUtBz+8H2OcpiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6z3qj3swz7g6c5qtwtyuzvm7nvxxjlvmuk8mnk00zc83yazpp7q4r0fpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubzQ2Z01LV1VrejNqeWY2
            anZEcCt4YUZlVE1PWGZnVU92NU1iVmVyMWlZCmtaZTZSTkYzOHYyRGtGWENqVSs1
            YkE0NG9tSlA0WmFlazVWdjBZczNnc3cKLS0tIENmY1kwTFY3c0VZS0ZJSzNTdys0
            ektOeDZ1MWZmMXlWSzZhTjhDYm1KN0UKnKbDPnBb6b14ZGmpLb1exf4Kni/l4wPy
            DbowVfOrEbBuiNOlfwhiwq8ZUGNAbIKAKgc1gUVuDPvCaPEIdeoCWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T11:00:00Z"
    mac: ENC[AES256_GCM,data:OYKeLS+1F5yiKhDTK27Rn5QamFa6JPZI3nbPEd6G7zDtZxwI8bhtyaM6yzK24u3nhsaKRptemg9har5yLneBdA44KW38ikt0X3rzXj+YRTTGZvIHyfp9TsjjzHRKPVuoWhwBi6/zVBegDS0Lot9ukckknRfbV4REcdb+rQVZmkw=,iv:Z2j1cc0hN/5hIg1MGIGGz3CZqrz4b8wOKvPjyubMeP0=,tag:/6u5C2ufywi/y29TOUgRWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
