apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: excalidraw-mcp-runtime
    namespace: excalidraw-mcp
spec:
    secretTemplates:
        - name: excalidraw-mcp-runtime
          stringData:
            MCP_AUTH_TOKEN: ENC[AES256_GCM,data:TIxj4tKNXMxaHi1MxJ9VgqICLpI71F+ZQX74SErw4YlXHGsUC/ASsmOtFA==,iv:DRpi9j9NO734jRwo9OrQSIlXRMPgff/yqFsHCpUwDPI=,tag:N5XOVlloLNkxGs3A16ZhJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6z3qj3swz7g6c5qtwtyuzvm7nvxxjlvmuk8mnk00zc83yazpp7q4r0fpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZXV3c0ROZ0hJcnEvbXpw
            L3I4VFNSRmlkT09WWlFRNU9EYkVNc1NpUDBrClRuME00UnVueDh4UHRYU2ErWHk4
            MHoyaitLT1orSmthbmV3OHZ0K2hVYTgKLS0tIHNPd1hQMUdHVkFvcURzZWhBY3hr
            ekI2eFFFU2VGeVBsdktxZGpNck9QNlUK1miP22e0SdxCJ7l/OAUEQz3xY3kgtf8X
            Q7ZAUGh/Byo6kNJ2b6pZAWwXiUUpSb9omMhqRH0Rl6G+fKulhoJ44w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T10:48:15Z"
    mac: ENC[AES256_GCM,data:+7eI4IVLNBICmoOrPHXnzqsCsg2rVy9XidvXGJpXY4JOM2Vv4vRizOSVnT5q1ExZW4FsdlTn6CQEBagQvwH4X6cxUdsVcbRPu3NbPz9aB0hHsejuLBpKrk3WCT2TmckOhvBC9gOwDd995N5fITrO12BDVQAwcvesor7if3UAFMg=,iv:P9XoXlJnKjVTEMQC5FUprPp8G1cSkb8ySZf9Gnuiz9g=,tag:bjLmD7oDzOmhWadC3TD0Og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
